//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Root {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public resExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Root.resExceptions", typeof(resExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The %var value specified for a set operation is equal to System.String.Empty (&quot;&quot;)..
        /// </summary>
        public static string ArgumentEmptyString {
            get {
                return ResourceManager.GetString("ArgumentEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %var is a null reference..
        /// </summary>
        public static string ArgumentNull {
            get {
                return ResourceManager.GetString("ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found exception occurred on %var method..
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was specifield FileMode.CreateNew flag and the file &quot;%var&quot; already exists..
        /// </summary>
        public static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;%var&quot; was not found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found exception occurred on %var method..
        /// </summary>
        public static string FileNotFoundOn {
            get {
                return ResourceManager.GetString("FileNotFoundOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format parameter does not contain a valid custom format pattern..
        /// </summary>
        public static string Format_InvalidString {
            get {
                return ResourceManager.GetString("Format_InvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operation, %var property was not set..
        /// </summary>
        public static string Invalid_PropNoSet {
            get {
                return ResourceManager.GetString("Invalid_PropNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument, don&apos;t match with compact format..
        /// </summary>
        public static string InvalidArg_CompactMatch {
            get {
                return ResourceManager.GetString("InvalidArg_CompactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument, don&apos;t match with standard format..
        /// </summary>
        public static string InvalidArg_StandardMatch {
            get {
                return ResourceManager.GetString("InvalidArg_StandardMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &quot;%var&quot; has invalid charaters..
        /// </summary>
        public static string InvalidChar_Key {
            get {
                return ResourceManager.GetString("InvalidChar_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section &quot;%var&quot; has invalid characters..
        /// </summary>
        public static string InvalidChar_Section {
            get {
                return ResourceManager.GetString("InvalidChar_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;%var&quot; has invalid characters..
        /// </summary>
        public static string InvalidChar_Value {
            get {
                return ResourceManager.GetString("InvalidChar_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;%var&quot; not is a valid file..
        /// </summary>
        public static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;%var&quot; has a invalid header..
        /// </summary>
        public static string InvalidHeader {
            get {
                return ResourceManager.GetString("InvalidHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask property is being set to a invalid value..
        /// </summary>
        public static string InvalidMask {
            get {
                return ResourceManager.GetString("InvalidMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operation, this instance is read-only..
        /// </summary>
        public static string InvalidWrite {
            get {
                return ResourceManager.GetString("InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &quot;%var&quot; was not found..
        /// </summary>
        public static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %var cannot be less than zero..
        /// </summary>
        public static string LessThanZero {
            get {
                return ResourceManager.GetString("LessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method {0} only works on Microsoft Windows 2000 or better..
        /// </summary>
        public static string NeedWin2000OrBetter {
            get {
                return ResourceManager.GetString("NeedWin2000OrBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of the type %var..
        /// </summary>
        public static string Obj_MustBeType {
            get {
                return ResourceManager.GetString("Obj_MustBeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %var property is being set to a null reference..
        /// </summary>
        public static string PropertyNull {
            get {
                return ResourceManager.GetString("PropertyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section &quot;%var&quot; was not found..
        /// </summary>
        public static string SectionNotFound {
            get {
                return ResourceManager.GetString("SectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %var1 length must be major than %var2 length..
        /// </summary>
        public static string StringMustMajorString {
            get {
                return ResourceManager.GetString("StringMustMajorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number %var is too big, the maximum supported value is %value..
        /// </summary>
        public static string TooBig_Number {
            get {
                return ResourceManager.GetString("TooBig_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %var1 length and/or %var2 value is too big..
        /// </summary>
        public static string TooBig_StringOrNumber {
            get {
                return ResourceManager.GetString("TooBig_StringOrNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number %var is too small, the minimum supported value is %value..
        /// </summary>
        public static string TooSmall_Number {
            get {
                return ResourceManager.GetString("TooSmall_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This NumberFormatInfo has a unsupported group size..
        /// </summary>
        public static string Unsupported_GroupSize {
            get {
                return ResourceManager.GetString("Unsupported_GroupSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name parameter specifies a culture that is not supported..
        /// </summary>
        public static string UnsupportedCulture {
            get {
                return ResourceManager.GetString("UnsupportedCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This number isn&apos;t supported with this NumberWriteInfo..
        /// </summary>
        public static string UnsupportedNumber_byNumberWriteInfo {
            get {
                return ResourceManager.GetString("UnsupportedNumber_byNumberWriteInfo", resourceCulture);
            }
        }
    }
}
